# Generated by Django 6.0.3 on 2026-04-18 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('SCHOOL', 'school'), ('UNIVERSITY', 'university'), ('COMPANY', 'company'), ('OTHER', 'other')], default='OTHER', max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('LEAD', 'lead'), ('CUSTOMER', 'customer')], default='NEW', max_length=255)),
                ('country', models.CharField(choices=[('RUSSIA', 'russia'), ('BELARUS', 'belarus'), ('KAZAKHSTAN', 'kazakhstan'), ('USA', 'usa'), ('EUROPE', 'europe'), ('OTHER', 'other')], default='OTHER', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
