# Generated by Django 6.0.3 on 2026-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'email', 'phone', 'account')},
        ),
    ]
