# Generated by Django 6.0.3 on 2026-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('customer', 'Customer'), ('lead', 'Lead')], default='new', max_length=255),
        ),
    ]
