# Generated by Django 6.0.3 on 2026-04-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_from_account', to='accounts.account'),
        ),
    ]
