# Generated by Django 6.0.3 on 2026-04-19 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='ACTIVE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'dollar'), ('RUB', 'ruble')], default='USD', max_length=10)),
                ('lms_course_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.CreateModel(
        #     name='ProductItem',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        #         ('quantity', models.PositiveIntegerField(default=1)),
        #         ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.course')),
        #     ],
        #     options={
        #         'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', False), ('contract__isnull', True)), models.Q(('deal__isnull', True), ('contract__isnull', False)), _connector='OR'), name='productitem_belongs_to_deal_xor_contract')],
        #     },
        # ),
    ]
