# Generated by Django 6.0.3 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('deals', '0002_alter_deal_unique_together_alter_deal_expected_value'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productitem',
            name='productitem_belongs_to_deal_xor_contract',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddConstraint(
            model_name='productitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', False), ('contract__isnull', True)), models.Q(('deal__isnull', False), ('contract__isnull', False)), _connector='OR'), name='productitem_belongs_to_deal_or_contract'),
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='unit_price',
        ),
    ]
