# Generated by Django 6.0.3 on 2026-04-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('deals', '0003_alter_deal_account_alter_deal_owner_and_more'),
        ('products', '0002_remove_productitem_productitem_belongs_to_deal_xor_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_productitems', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_productitems', to='products.course'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_productitems', to='deals.deal'),
        ),
    ]
