# Generated by Django 6.0.3 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
