# Generated by Django 6.0.3 on 2026-04-22 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contact_unique_together'),
        ('contracts', '0002_contract_created_at_contract_start_date_and_more'),
        ('deals', '0001_initial'),
        ('products', '0002_delete_productitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deal',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_on_deal', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_deals', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], default='open', max_length=32),
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('access_months', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis_from_course', to='products.course')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis_from_deal', to='deals.deal')),
            ],
        ),
    ]
