# Generated by Django 6.0.3 on 2026-04-24 05:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_unique_together_deal_contract_and_more'),
        ('products', '0002_delete_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='title',
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='di_from_course', to='products.course'),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='di_from_deal', to='deals.deal'),
        ),
    ]
