# Generated by Django 6.0.3 on 2026-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_deal_title_alter_deal_expected_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
