[pytest]
pythonpath = djangoproject
DJANGO_SETTINGS_MODULE = backend.settings
python_files = tests.py test_*.py *_tests.py
markers =
    e2e: end-to-end tests (api tests)
    integration: integrations tests (service-reppo-mapper-domain-orm relationship)
    unit: unit tests (business logic)
    user: tests bounded to user context
    product: tests bounded to product ccontext
    deal: tests bounded to deal ccontext