# Generated by Django 6.0.3 on 2026-04-17 16:34
from django.db import migrations
from djangoproject.backend.structures import GroupEnum

def create_groups(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')
    for group in GroupEnum:
        Group.objects.get_or_create(name=group.value)

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group in GroupEnum:
        Group.objects.filter(name=group.value).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0001_initial') #trying to import auth module (with groups)
    ]

    operations = [
        migrations.RunPython(code=create_groups, reverse_code=delete_groups) # reverse will work if main operation failed
    ]