# Generated by Django 6.0.3 on 2026-04-24 06:11
from uuid import uuid4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_created_at_contract_start_date_and_more'),
        ('deals', '0003_remove_deal_title_alter_deal_expected_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.OneToOneField(default=uuid4(), on_delete=django.db.models.deletion.PROTECT, related_name='contract_from_deal', to='deals.deal'),
            preserve_default=False,
        ),
    ]
