# Generated by Django 6.0.3 on 2026-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
    ]
