# Generated by Django 6.0.3 on 2026-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_deal_remove_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
